name: Hello GitHub Actions

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Dotnet info
      - run: dotnet --info

      - name: Dotnet restore
      - run: dotnet restore

      - name: Dotnet build
      - run: dotnet build --configuration Release

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show operating system
        run: uname -a

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Show current time
        run: date